### ISSUE TITLE
[Meta] Willing to accept updates?

### ISSUE THREAD

**Issue by stavro** [sikanhe/algolia-elixir#1]
Hi @sikanhe, thanks for the work on this so far.

I'm evaluating using this library for a project of mine, but I'm going to need to invest some work to fill out some of the missing API calls and expand on what's already here.

Are you open to contributions and are you open to overall code structure improvements?

If so, let me know ASAP and please add a license file to this project (preferably Apache, the same license as Elixir).

**Comment by sikanhe** [comment]
@stavro yes, contributions are welcome! And I will add a license file asap.

**Comment by sikanhe** [comment]
added via 8afaf49c62364718022181442e2ff87a682d37af
