### ISSUE TITLE
Thanks for the plugin

### ISSUE THREAD

**Issue by pixelastic** [sikanhe/algolia-elixir#2]
Hello,

Sorry to contact you through your issues, but I could not find another way from your profile page.

I wanted to thank you for the work you put into this plugin. I work at Algolia, and it is always a joy to see people from the community building stuff with our API, so thank you.

Feel free to send me an email at tim at algolia dot com for a real thank you gift :)

**Comment by sikanhe** [comment]
sent you an email :)
