### ISSUE TITLE
Save an Object without OBJECT ID

### ISSUE THREAD

**Issue by musfiqurcse** [sikanhe/algolia-elixir#3]
It is undoubtedly best Elixir Algolia Client API Library. However, I figure out that the library missed a functionalities that is to save an object without passing `object-ID` . 

I figure out some feature is missing.
They are 

1. Batch File Save
2. Batch File Save in Multiple Indexes

**Comment by sikanhe** [comment]
Algolia requires you to specify an object id for each doc. 

Multi index is already implemented by using multi : https://github.com/sikanhe/algolia-elixir#multiple-queries-at-once 

Batch save: https://github.com/sikanhe/algolia-elixir/blob/master/lib/algolia.ex#172

**Comment by sikanhe** [comment]
I am guessing that you want the functionality for algolia to generate an objectID by itself ?

**Comment by sikanhe** [comment]
add_object and add_objects without objectID feature is now added with version 0.4.0
