### ISSUE TITLE
Trying to use this package, without luck, any help?

### ISSUE THREAD

**Issue by vvo** [sikanhe/algolia-elixir#30]
Hi there, we got a customer request trying to use this package and it was failing for some reason.

Trying to use this package myself I also failed at it. I made an example GitHub repository here: https://github.com/algolia/elixir-test

Could you have a look and tell me what's wrong?

Thanks!

**Comment by davidbrusius** [comment]
Hi @vvo, just opened a PR in the repo fixing the issue.
