### ISSUE TITLE
delete_object with empty string deletes the index

### ISSUE THREAD

**Issue by stavro** [sikanhe/algolia-elixir#6]
An object id of an empty string deletes the entire index due to the way strings are concatenated.

`Algolia.delete_object(index_name, "")`

This probably shouldn't be allowed.

It'd be nice to get https://github.com/sikanhe/algolia-elixir/pull/5 merged in during a fix for this also.

**Comment by sikanhe** [comment]
thanks for spotting that, will take a look at it today
