### ISSUE TITLE
Update Poison dependency

### ISSUE THREAD

**Issue by chvanikoff** [sikanhe/algolia-elixir#8]
Hi, Phoenix 1.3 is almost out and it depends on Poison ~> 2.2 or ~> 3.0. It seems updating poison dependency to `~> 1.5 or ~> 2.2 or ~> 3.0` will not break anything in the project but will bring happiness to those who is using Phoenix 1.3 with Algolia :)

**Comment by sikanhe** [comment]
@chvanikoff Do you mind doing a quick PR for this ?

**Comment by chvanikoff** [comment]
sure, will send one soon

**Comment by chvanikoff** [comment]
@sikanhe don't you mind updating hackney from 1.6.5 to 1.8.6 as well? Checked it and didn't found any backward-incompatible changes.

**Comment by sikanhe** [comment]
that's fine, maybe `1.6.5 or 1.7.1 or 1.8.6` ?

**Comment by chvanikoff** [comment]
Well, it's possible to use ~> 1.6 then, but I don't think it's really needed as for Poison where versions difference is in major tags. However, it's up to you to make a final decision.

**Comment by sikanhe** [comment]
~> 1.6 would only work for 1.6.x I believe.

**Comment by chvanikoff** [comment]
No, it'll match `>= 1.6 and < 2.0`, you can check out docs for versioning in Elixir here: https://hexdocs.pm/elixir/Version.html

**Comment by sikanhe** [comment]
Oh interesting, I never knew that. I think its better to be requiring specific versions in this situation. We don't want unexpected breaking changes due to newer versions being acquired automatically.

**Comment by chvanikoff** [comment]
Ok, there you go, but I've set ~> instead of specific versions to stay up-to-date with minor non-breaking patches without requiring to update this lib. By the way, semantic versioning assumes that no breaking changes are introduced between non-major (1.6 -> 1.7 -> 1.8) patches.

**Comment by sikanhe** [comment]
@chvanikoff  thanks, that's usually true but there was this mess not long ago: https://github.com/edgurgel/httpoison/issues/130
